### ISSUE TITLE
存在しないスレッドのとき、404を表示

### ISSUE THREAD

**Issue by thori0908** [Naoya-Kojima/BBS#20]
存在しないスレッドの詳細ページを開いた時、これだとエラーになるのでは？
https://github.com/Naoya-Kojima/BBS/blob/master/app/controllers/posts_controller.rb#L12-L15

**Comment by Naoya-Kojima** [comment]
### 仕様
存在しないスレッドの詳細ページを開いた時、ActiveRecord::RecordNotFoundエラーが出るため、
404 Not foundを表示させるようにする

**Comment by Naoya-Kojima** [comment]
### テストケース
## スレッド詳細ページ
/posts/:id
- 存在しないスレッド詳細ページのとき404 Not Foundエラーが表示される

### どのようにして動作確認を行うか
- 存在しないスレッドの詳細を表示させ、404が表示される
- 存在するスレッドにもアクセスして詳細ページが表示される
