### ISSUE TITLE
post_controllerを作成

### ISSUE THREAD

**Issue by Naoya-Kojima** [Naoya-Kojima/BBS#4]
post_controllerを作成し、
必要なアクション、viewを実装する。

**Comment by thori0908** [comment]
スレッドの詳細（posts_controller.show）で
- [ ] ユーザーがスレッドにコメントできる
  - ログインしてないユーザーもコメントできる
- [ ] ユーザーのコメントを表示
  - [ ] コメント文を表示
  - [ ] コメントしたユーザー名を表示。ログインしてないユーザーは "匿名"と表示
